fix = true

line-length = 160

exclude = ["migrations", "*.html"]

lint.select = ["E", "F", "I", "UP", "B", "PERF", "FIX002", "PLE", "PLW", "F822"]
lint.ignore = ["E501", "D104", "D100"]
lint.exclude = [".git", "__pycache__", "venv", ".venv"]

lint.flake8-quotes.docstring-quotes = "double"

format.quote-style = "double"
format.indent-style = "space"
format.line-ending = "auto"
format.skip-magic-trailing-comma = false
format.docstring-code-format = true